### ISSUE TITLE
neg标签列表的生成能否确保是负样本

### ISSUE THREAD

**Issue by CuAlB** [LirongWu/TGS#1]
您好，很高兴能够看到一个在cora上能达到85准确率的纯MLP模型，但我注意到neg的生成使用了neg = torch.randint(0, n_nodes, (n_edges, ))，这样实现的话感觉可能会让节点的邻居(即正样本)也算入其中，可能在特征级自蒸馏中造成一定的影响，不过我修改neg的生成后发现对准确率没有特别大的影响，因此感到有些困惑，期待与您进一步交流

**Comment by LirongWu** [comment]
邻居节点（正样本）确实有几率被采样到，不过相比于非邻居节点，它们被采样的概率更低。在常见的对比学习范式中，比如采用InforNCE损失，分母项中可能同时包含少数正样本和多数负样本，但并不必然会对性能产生很大的影响。当然，负样本挖掘（比如在负样本中特别地排除邻居节点正样本的影响）是一个很热门的研究问题，尤其在图对比学习领域，但在这篇文章中没有重点关注这个问题。

**Comment by CuAlB** [comment]
明白了，谢谢您，期待未来攻读研究生时与您相见
